addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.11")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.0.0-M2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.8")
addSbtPlugin("com.twitter" % "scrooge-sbt-plugin" % "19.9.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.3.5")
